---
name: Build
on: push

jobs:
  go-lint:
    name: Linting
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3.1.0
      - uses: actions/setup-go@v3.3.1
        with:
          go-version: "1.19.2"
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3.3.1
        with:
          version: v1.50.1

  super-linter:
    name: Run GitHub super-linter
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3.1.0
      - uses: github/super-linter@v4.9.7
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  go-test:
    name: Run tests
    runs-on: ubuntu-22.04
    needs: go-lint
    steps:
      - uses: actions/checkout@v3.1.0
      - uses: actions/setup-go@v3.3.1
        with:
          go-version: "1.19.2"
      - run: go build -v
      - run: go test ./...
