---
name: Build
on: push

jobs:
  build:
    name: Build and Lint
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3.1.0
      - uses: actions/setup-go@v3.4.0
        with:
          go-version: "1.19.2"
      - run: go build -v
      - run: go test ./...
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3.3.1
        with:
          version: v1.50.1
      - uses: github/super-linter@v4.9.7
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_GO: false
